#cargo-features = ["codegen-backend"]

[workspace]
resolver = "3"
members = ["audio", "core", "event-derive", "graphics", "graphics_core", "quickstart","event-derive"]
#remove when ready
publish = false

[package]
name = "age_engine"
version = "0.1.0"
edition = "2024"
authors = ["Jonathan Schmittat"]

[dependencies]
#graphics={path="./graphics"}
#graphics_core={path="./graphics_core"}
audio={path="./audio"}
#quickstart={path="./quickstart"}
core={path="./core"}
event-derive={path="./event-derive"}




[build]
rustflags = ["-Z", "threads=8"]


#[profile.dev]
#codegen-backend = "cranelift"
