[package]
name = "event_derive"
version = "0.1.1"
edition = "2024"

[lib]
proc-macro = true

[dependencies]
quote="1.0.40"
proc-macro2 = "1.0.95"

[dependencies.syn]
version="2.0.104"
default-features = false
features = ["parsing","derive","proc-macro"]
